version: "3"
services:
  chatgpt-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: ivanglie/chatgpt-bot:latest
    container_name: chatgpt-bot
    restart: always
    ports:
      - "18080:18080"
    environment:
      - BOT_TOKEN
      - OPENAI_API_KEY
      - BOT_USERS